### ISSUE TITLE
ValueError Expected singleton

### ISSUE THREAD

**Issue by lucasub** [OCA/server-ux#147]
Hello, with odoo 12.0 and mass_editing version 12.0.1.0.0 I received this error message
when try to set boolean flag "is_published" on product_template:

Traceback (most recent call last):
  File "/home/odoo/v12/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/v12/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/odoo/v12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/odoo/v12/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/v12/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/v12/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/v12/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/v12/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/v12/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/v12/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/v12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/v12/odoo/odoo/api.py", line 757, in call_kw
    return _call_kw_model_create(method, model, args, kwargs)
  File "/home/odoo/v12/odoo/odoo/api.py", line 737, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-98>", line 2, in create
  File "/home/odoo/v12/odoo/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/home/odoo/v12/addons_extra/mass_editing/wizard/mass_editing_wizard.py", line 282, in create
    self.env.context.get('active_ids')).write(values)
  File "/home/odoo/v12/addons_extra/product_barcode/models/product_form.py", line 95, in write
    code = "8099997{:0>5}".format(self.id)
  File "/home/odoo/v12/odoo/odoo/fields.py", line 2887, in __get__
    raise ValueError("Expected singleton: %s" % record)
ValueError: Expected singleton: product.template(456, 1923, 1926, 930, 1911, 1914, 460, 457, 458, 459, 928, 439, 440, 433, 434, 435, 432, 436, 431, 438, 437, 444, 445, 446, 441, 443, 442, 454, 929, 455, 449, 14786, 1917, 1920, 452, 925, 453, 447, 448, 450, 451, 486, 1924, 1927, 935, 1913, 1915, 490, 487, 488, 489, 933, 469, 470, 463, 464, 465, 462, 466, 461, 468, 467, 474, 475, 476, 471, 473, 472, 484, 934, 485, 479, 14787, 1918, 1921, 482, 932, 483, 477, 478)

How can I resolve the problem?
Thank you
Luca

**Comment by jomardotdeveloper** [comment]
Kaya mo yan boss
