### ISSUE TITLE
Error installing mass editing v13

### ISSUE THREAD

**Issue by pprasquier** [OCA/server-ux#231]
We get the following error when trying to install mass_editing_v13-13.0.1.1.0.zip on our odoo.sh v13 instance

2020-11-06 01:28:13,497 6 INFO al1p-patibio-development-1662485 odoo.modules.loading: loading 78 modules...
2020-11-06 01:28:13,652 6 CRITICAL al1p-patibio-development-1662485 odoo.modules.module: Couldn't load module mass_editing_v13
2020-11-06 01:28:13,661 6 CRITICAL al1p-patibio-development-1662485 odoo.modules.module: No module named 'odoo.addons.mass_editing'
2020-11-06 01:28:13,665 6 WARNING al1p-patibio-development-1662485 odoo.modules.loading: Transient module states were reset
2020-11-06 01:28:13,667 6 ERROR al1p-patibio-development-1662485 odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 423, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 182, in load_module_graph
    load_openerp_module(package.name)
  File "/home/odoo/src/odoo/odoo/modules/module.py", line 376, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/home/odoo/src/user/mass_editing_v13/__init__.py", line 7, in <module>
    from . import tests
  File "/home/odoo/src/user/mass_editing_v13/tests/__init__.py", line 5, in <module>
    from . import test_mass_editing
  File "/home/odoo/src/user/mass_editing_v13/tests/test_mass_editing.py", line 9, in <module>
    from odoo.addons.mass_editing.hooks import uninstall_hook
ModuleNotFoundError: No module named 'odoo.addons.mass_editing'
2020-11-06 01:28:13,668 6 CRITICAL al1p-patibio-development-1662485 odoo.service.server: Failed to initialize database `al1p-patibio-development-1662485`. 
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/service/server.py", line 1190, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 423, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 182, in load_module_graph
    load_openerp_module(package.name)
  File "/home/odoo/src/odoo/odoo/modules/module.py", line 376, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/home/odoo/src/user/mass_editing_v13/__init__.py", line 7, in <module>
    from . import tests
  File "/home/odoo/src/user/mass_editing_v13/tests/__init__.py", line 5, in <module>
    from . import test_mass_editing
  File "/home/odoo/src/user/mass_editing_v13/tests/test_mass_editing.py", line 9, in <module>
    from odoo.addons.mass_editing.hooks import uninstall_hook
ModuleNotFoundError: No module named 'odoo.addons.mass_editing'

**Comment by teds-it** [comment]
Had a similar error while installing. fixed it by renaming the addon folder mass_editing_v13 to mass_editing. Seems like some code is expecting a folder name without _v13.

Greetz,
Ted

**Comment by pedrobaeza** [comment]
You have downloaded another version that is not this one
