### ISSUE TITLE
[11.0] easy_switch_user  Uncaught TypeError: this._rpc is not a function

### ISSUE THREAD

**Issue by m3asmi** [OCA/server-ux#35]
I installed the module in the Enterprise edition I got this error : 
` Uncaught TypeError: this._rpc is not a function`<br/>
`http://localhost:8069/easy_switch_user/static/src/js/switch_user.js:26
Retraçage :
TypeError: this._rpc is not a function
    at Class.loadUsers (http://localhost:8069/easy_switch_user/static/src/js/switch_user.js:26:25)
    at Class.start (http://localhost:8069/easy_switch_user/static/src/js/switch_user.js:22:18)
    at Class.prototype.(anonymous function) [as start] (http://localhost:8069/web/static/src/js/framework/class.js:89:38)
    at http://localhost:8069/web/static/src/js/framework/widget.js:193:25
    at http://localhost:8069/web/static/lib/jquery/jquery.js:3276:89
    at fire (http://localhost:8069/web/static/lib/jquery/jquery.js:3119:58)
    at Object.add [as done] (http://localhost:8069/web/static/lib/jquery/jquery.js:3165:49)
    at Array.<anonymous> (http://localhost:8069/web/static/lib/jquery/jquery.js:3275:77)
    at Function.each (http://localhost:8069/web/static/lib/jquery/jquery.js:383:58)
    at Object.<anonymous> (http://localhost:8069/web/static/lib/jquery/jquery.js:3272:56)`

**Comment by pedrobaeza** [comment]
Maybe the module is not compatible with enterprise edition, but this can't be tried as that edition is closed source.
