### ISSUE TITLE
[14.0] ValueError in base_search_custom_field_filter module with demo date

### ISSUE THREAD

**Issue by zzwxrchi** [OCA/server-ux#407]
module: base_search_custom_field_filter
version: 14.0

**Steps to reproduce**
- Run official odoo 14.0 docker image with l10n-spain addons, its required OCA addons and all python dependencies.
- Create a test db **with demo date**
- Install Sales app and base_search_custom_field_filter module
- Go to Sales -> Orders -> Customers
- Quite "Customers Invoices" filter
- Enter "English"
- Clic filter "English(US)" at below

**Current behavior**
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1347, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1366, in do_search_read
    return Model.web_search_read(domain, fields, offset=offset, limit=limit, order=sort)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/models/models.py", line 62, in web_search_read
    records = self.search_read(domain, fields, offset=offset, limit=limit, order=order)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4823, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1708, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/res_partner.py", line 754, in _search
    count=count, access_rights_uid=access_rights_uid)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4495, in _search
    query = self._where_calc(args)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4251, in _where_calc
    return expression.expression(domain, self).query
  File "/usr/lib/python3/dist-packages/odoo/osv/expression.py", line 442, in __init__
    self.parse()
  File "/usr/lib/python3/dist-packages/odoo/osv/expression.py", line 654, in parse
    raise ValueError("Invalid field %s.%s in leaf %s" % (model._name, path[0], str(leaf)))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field res.partner.ir_ui_custom_filter_1 in leaf ('ir_ui_custom_filter_1', '=', 'en_US')

**Expected behavior**
Filter customers with language "English"

The module is in beta state, report only for feedback.

**Comment by pedrobaeza** [comment]
See #364

**Comment by zzwxrchi** [comment]
Thanks @pedrobaeza !!

Even if I modify code as [364](https://github.com/OCA/server-ux/pull/364/files) 
Or as [c335dd0](https://github.com/OCA/server-ux/commit/c335dd09a4c05eb497a615e57200a62559c3ba5a)

I don't fix the error

**Comment by zzwxrchi** [comment]
Ok I got it. Just need to restart the server, since we changed the .py files.

I applied both changes [c335dd0](https://github.com/OCA/server-ux/commit/c335dd09a4c05eb497a615e57200a62559c3ba5a) and [364](https://github.com/OCA/server-ux/pull/364/files) in the code.

Thank you very much !!
