### ISSUE TITLE
products mass editing V11 CE error on adding fields

### ISSUE THREAD

**Issue by specitsystems** [OCA/server-ux#46]
When adding fields for Product template:
getting the following 

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/odoo-server/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 876, in search_read
    return self.do_search_read(model, fields, offset, limit, domain, sort)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 898, in do_search_read
    offset=offset or 0, limit=limit or False, order=sort or False)
  File "/odoo/odoo-server/odoo/models.py", line 4223, in search_read
    records = self.search(domain or [], offset=offset, limit=limit, order=order)
  File "/odoo/odoo-server/odoo/addons/mass_editing/models/ir_model_fields.py", line 24, in search
  File "/odoo/odoo-server/odoo/models.py", line 1481, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/odoo/odoo-server/odoo/models.py", line 3774, in _search
    query = self._where_calc(args)
  File "/odoo/odoo-server/odoo/models.py", line 3564, in _where_calc
    e = expression.expression(domain, self)
  File "/odoo/odoo-server/odoo/osv/expression.py", line 668, in __init__
    self.parse()
  File "/odoo/odoo-server/odoo/osv/expression.py", line 846, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'mass_editing_domain' in leaf "<osv.ExtendedLeaf: ('mass_editing_domain', 'in', '[146]') on ir_model_fields (ctx: )>"

**Comment by pedrobaeza** [comment]
Have you tried to reproduce the problem in our OCA runbot?

**Comment by astirpe** [comment]
I cannot reproduce the problem in V11 CE

**Comment by PhatDang** [comment]
Can you try like this:
```python
@api.model
    def search(self, args, offset=0, limit=0, order=None, count=False):
        model_domain = []
        for domain in args:
            if (len(domain) > 2 and domain[0] == 'mass_editing_domain' and
                    isinstance(domain[2], str) and
                    list(domain[2][1:-1])):
                model_domain += [('model_id', 'in',
                                  [int(x) for x in domain[2][1:-1].split(',')]
                                  )]
            else:
                # model_domain.append(domain)
                continue

        return super(IrModelFields, self).search(model_domain, offset=offset,
                                                 limit=limit, order=order,
                                                 count=count)
```
