### ISSUE TITLE
[14.0][mass_editing] Not working with one2many fields

### ISSUE THREAD

**Issue by colmeirin** [OCA/server-ux#461]
## Module
mass_editing

## Describe the bug
Not working with one2many fields.

## To Reproduce
**Affected versions**:
14.0
1. go to runboat
2. go to settings > techincal > actions > server actions and create a new server action of type mass edit records.
3. add a model and a one2many fields. Examples: Model:contact, field:contact | Model:contact, field:banks, | model:product template, field:suppliers...
4. go to model and launch mass editing created and when clicking on "Add a line" at the one2many field the error is thrown.

**Expected behavior**
To be able to mass edit one2many fields

**Additional context**
Sample stacktrace of the error in runboat attached. It fails with field "message" but it also fails with all de fields updated in the default_get function of the wizard.

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/http.py", line 914, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 1394, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/main.py", line 1386, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/models.py", line 6230, in onchange
    record._update_cache(changed_values, validate=False)
  File "/opt/odoo/odoo/models.py", line 5172, in _update_cache
    cache.set(self, field, field.convert_to_cache(value, self, validate))
  File "/opt/odoo/odoo/fields.py", line 2658, in convert_to_cache
    id_ = comodel.new(value, origin=origin).id
  File "/opt/odoo/odoo/models.py", line 5526, in new
    record._update_cache(values, validate=False)
  File "/opt/odoo/odoo/models.py", line 5168, in _update_cache
    raise ValueError("Invalid field %r on model %r" % (e.args[0], self._name))
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Invalid field 'message' on model 'res.partner'

**Comment by Tatider** [comment]
The same problem exists for version 15.0

**Comment by JoelZilli** [comment]
The same problem exists for version 13.0
