### ISSUE TITLE
Updating date_range to 14.0.2.1.1 gives an error coming from 14.0.2.0.2

### ISSUE THREAD

**Issue by Stephanisk** [OCA/server-ux#574]
Below is the error code i received upon trying to install: 

I can not create date ranges in payroll ( latest version OCA ) i supposed it to be an error in date_range so tried updating this. But following error occurs.

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/odoo/odoo-server/odoo/models.py", line 4245, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/odoo/odoo-server/odoo/models.py", line 4161, in _load_records_create
    return self.create(values)
  File "<decorator-gen-51>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 329, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/odoo/odoo-server/odoo/api.py", line 329, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/odoo/odoo-server/odoo/addons/base/models/ir_cron.py", line 71, in create
    return super(ir_cron, self).create(values)
  File "<decorator-gen-64>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 347, in _model_create_multi
    return create(self, [arg])
  File "/odoo/odoo-server/odoo/addons/base/models/ir_fields.py", line 534, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/odoo/models.py", line 3877, in create
    parents = self.env[model_name].create([
  File "<decorator-gen-45>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_actions.py", line 47, in create
    res = super(IrActions, self).create(vals_list)
  File "<decorator-gen-64>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_fields.py", line 534, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/odoo/odoo-server/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo-server/odoo/models.py", line 3885, in create
    records = self._create(data_list)
  File "/odoo/odoo-server/odoo/models.py", line 3991, in _create
    cr.execute(query, params)
  File "<decorator-gen-3>", line 2, in execute
  File "/odoo/odoo-server/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/sql_db.py", line 300, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.NotNullViolation: null value in column "activity_user_type" of relation "ir_act_server" violates not-null constraint
DETAIL:  Failing row contains (824, Auto-generate date ranges, ir.actions.server, null, null, action, list,form, 1, 2023-01-07 21:53:58.006773, 1, 2023-01-07 21:53:58.006773, ir_cron, code, 5, 674, null, model.autogenerate_ranges(), null, null, null, null, null, null, null, null, null, null, null, null, null).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/odoo/odoo-server/odoo/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo-server/odoo/http.py", line 361, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo-server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo-server/odoo/http.py", line 349, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 914, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo-server/odoo/http.py", line 533, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1392, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo-server/addons/web/controllers/main.py", line 1380, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo-server/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-77>", line 2, in button_immediate_upgrade
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 658, in button_immediate_upgrade
    return self._button_immediate_function(type(self).button_upgrade)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_module.py", line 596, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo-server/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 455, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/odoo/odoo-server/odoo/modules/loading.py", line 347, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/odoo/odoo-server/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/odoo/odoo-server/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/odoo/odoo-server/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/odoo/odoo-server/odoo/tools/convert.py", line 681, in _tag_root
    raise ParseError('while parsing %s:%s, near\n%s' % (
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo-server/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /odoo/custom/addons/date_range/data/ir_cron_data.xml:3, near
<record model="ir.cron" id="ir_cron_autocreate">
        <field name="name">Auto-generate date ranges</field>
        <field name="interval_number">1</field>
        <field name="interval_type">days</field>
        <field name="numbercall">-1</field>
        <field name="active">True</field>
        <field name="doall" eval="False"/>
        <field name="model_id" ref="model_date_range_type"/>
        <field name="state">code</field>
        <field name="code">model.autogenerate_ranges()</field>
    </record>

**Comment by rrebollo** [comment]
@Stephanisk I'm currently facing the same problem. Did U find any workaround? @StefanRijnhart looks like the last contributor to ir_cron_data.xml. The only way to reproduce error is updating from old versions to recent ones.

```
bad query: INSERT INTO "ir_act_server" ("id", "create_uid", "create_date", "write_uid", "write_date", "binding_type", "binding_view_types", "code", "model_id", "name", "sequence", "state", "type", "usage") VALUES (nextval('ir_actions_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), 'action', 'list,form', 'model.autogenerate_ranges()', 611, 'Auto-generate date ranges', 5, 'code', 'ir.actions.server', 'ir_cron') RETURNING id
ERROR: null value in column "activity_user_type" of relation "ir_act_server" violates not-null constraint
DETAIL:  Failing row contains (794, Auto-generate date ranges, ir.actions.server, null, null, action, list,form, 1, 2024-10-17 14:36:47.08848, 1, 2024-10-17 14:36:47.08848, ir_cron, code, 5, 611, null, model.autogenerate_ranges(), null, null, null, null, null, null, null, null, null, null, null, null, null).
```
```
Failed to load registry
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/odoo/src/odoo/odoo/models.py", line 4265, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/odoo/src/odoo/odoo/models.py", line 4170, in _load_records_create
    return self.create(values)
  File "<decorator-gen-53>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 333, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/odoo/src/odoo/odoo/api.py", line 333, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_cron.py", line 72, in create
    return super(ir_cron, self).create(values)
  File "<decorator-gen-66>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 352, in _model_create_multi
    return create(self, [arg])
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_fields.py", line 534, in create
    recs = super().create(vals_list)
  File "<decorator-gen-15>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 353, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/odoo/models.py", line 3891, in create
    parents = self.env[model_name].create([
  File "<decorator-gen-47>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 353, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_actions.py", line 48, in create
    res = super(IrActions, self).create(vals_list)
  File "<decorator-gen-66>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 353, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_fields.py", line 534, in create
    recs = super().create(vals_list)
  File "<decorator-gen-15>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 353, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/odoo/models.py", line 3899, in create
    records = self._create(data_list)
  File "/home/odoo/src/odoo/odoo/models.py", line 4005, in _create
    cr.execute(query, params)
  File "<decorator-gen-5>", line 2, in execute
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/sql_db.py", line 301, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.NotNullViolation: null value in column "activity_user_type" of relation "ir_act_server" violates not-null constraint
DETAIL:  Failing row contains (794, Auto-generate date ranges, ir.actions.server, null, null, action, list,form, 1, 2024-10-17 14:36:47.08848, 1, 2024-10-17 14:36:47.08848, ir_cron, code, 5, 611, null, model.autogenerate_ranges(), null, null, null, null, null, null, null, null, null, null, null, null, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 455, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 347, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 681, in _tag_root
    raise ParseError('while parsing %s:%s, near\n%s' % (
odoo.tools.convert.ParseError: while parsing /home/odoo/src/user/OCA/server-ux/date_range/data/ir_cron_data.xml:3, near
<record model="ir.cron" id="ir_cron_autocreate">
        <field name="name">Auto-generate date ranges</field>
        <field name="interval_number">1</field>
        <field name="interval_type">days</field>
        <field name="numbercall">-1</field>
        <field name="active">True</field>
        <field name="doall" eval="False"/>
        <field name="model_id" ref="model_date_range_type"/>
        <field name="state">code</field>
        <field name="code">model.autogenerate_ranges()</field>
    </record>
```

**Comment by rrebollo** [comment]
It's interesting if U follow traceback there is no call to mail addon where ir.actions.server get the activity related features.
https://github.com/odoo/odoo/blob/f2765d2cab5671a010404c36842bf1b4c4d6350b/addons/mail/models/ir_actions.py#L42

**Comment by StefanRijnhart** [comment]
Weird bug in Odoo 14: a module that only depends on `base` can break on this required field from mail (https://github.com/odoo/odoo/blob/14.0/addons/mail/models/ir_actions.py#L42-L45) if cron data is updated before the mail module is loaded (so that no default is provided for the column).

Fixed in Odoo 15 as the field was removed from the mail module. Try adding mail as a dependency temporarily.

**Comment by rrebollo** [comment]
> Weird bug in Odoo 14: a module that only depends on `base` can break on this required field from mail (https://github.com/odoo/odoo/blob/14.0/addons/mail/models/ir_actions.py#L42-L45) if cron data is updated before the mail module is loaded (so that no default is provided for the column).
> 
> Fixed in Odoo 15 as the field was removed from the mail module. Try adding mail as a dependency temporarily.

Why don't record the dependency right in data_range addon 14.0 branch???

**Comment by rrebollo** [comment]
As a workareound:
```
ALTER TABLE ir_act_server ALTER COLUMN activity_user_type SET DEFAULT 'specific';
ALTER TABLE ir_act_server ALTER COLUMN activity_user_type DROP NOT NULL;
```
