### ISSUE TITLE
[16.0] date_range lost compatibility with web_advanced_search

### ISSUE THREAD

**Issue by kikopeiro** [OCA/server-ux#722]
## Module
date_range

## Describe the bug
After https://github.com/OCA/server-ux/pull/717 web_advanced_search is not working properly, throws this error

```
OwlError: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (https://XXXXXXXXXXXXXXXXXX/web/assets/1122-191e1e2/web.assets_common.min.js:1472:101)
    at owl.App.handleError (https://XXXXXXXXXXXXXXXXXX/web/assets/1122-191e1e2/web.assets_common.min.js:2098:29)
    at RootFiber._render (https://XXXXXXXXXXXXXXXXXX/web/assets/1122-191e1e2/web.assets_common.min.js:1497:19)
    at RootFiber.render (https://XXXXXXXXXXXXXXXXXX/web/assets/1122-191e1e2/web.assets_common.min.js:1495:6)
    at ComponentNode.render (https://XXXXXXXXXXXXXXXXXX/web/assets/1122-191e1e2/web.assets_common.min.js:1571:56)

Caused by: TypeError: Cannot read properties of undefined (reading '0')
    at CustomFilterItem.setDefaultValue (https://XXXXXXXXXXXXXXXXXX/web/assets/1167-8cb4da3/web.assets_backend.min.js:1837:154)
    at CustomFilterItem.setDefaultValue (https://XXXXXXXXXXXXXXXXXX/web/assets/1167-8cb4da3/web.assets_backend.min.js:15435:459)
    at setDefaultValue (patch date_range.CustomFilterItem) (https://XXXXXXXXXXXXXXXXXX/web/assets/1167-8cb4da3/web.assets_backend.min.js:1657:22)
    at CustomFilterItem.setDefaultValue (https://XXXXXXXXXXXXXXXXXX/web/assets/1167-8cb4da3/web.assets_backend.min.js:15235:579)
    at setDefaultValue (patch web_advanced_search.CustomFilterItem) (https://XXXXXXXXXXXXXXXXXX/web/assets/1167-8cb4da3/web.assets_backend.min.js:1657:22)
    at CustomFilterItem.addNewCondition (https://XXXXXXXXXXXXXXXXXX/web/assets/1167-8cb4da3/web.assets_backend.min.js:1835:155)
    at CustomFilterItem.setup (https://XXXXXXXXXXXXXXXXXX/web/assets/1167-8cb4da3/web.assets_backend.min.js:1834:392)
    at CustomFilterItem.setup (https://XXXXXXXXXXXXXXXXXX/web/assets/1167-8cb4da3/web.assets_backend.min.js:15434:484)
    at setup (patch date_range.CustomFilterItem) (https://XXXXXXXXXXXXXXXXXX/web/assets/1167-8cb4da3/web.assets_backend.min.js:1657:22)
    at CustomFilterItem.setup (https://XXXXXXXXXXXXXXXXXX/web/assets/1167-8cb4da3/web.assets_backend.min.js:15235:421)
```

## To Reproduce
**Affected versions**:

1. with date_range and web_advanced_search installed 
2. On valuation report (stock_account)  Inventory> Reporting>Valuation (similar response could have with other model )
3. Click inside "Filters" and move your mouse between "Group By" and "Filters"

https://github.com/OCA/server-ux/assets/4610000/1adf4f96-775c-470d-a79f-8cfe954ee420

CC @CarlosRoca13

**Comment by pedrobaeza** [comment]
He is on holidays, so please research the possible fix.

**Comment by kikopeiro** [comment]
Perfect! This issue seems that  have been fixed!

Thanks @hugosantosred
