### ISSUE TITLE
[15.0] Branch tests are broken

### ISSUE THREAD

**Issue by bosd** [OCA/server-ux#734]
Branch tests are broken
as dicovered in: https://github.com/OCA/server-ux/pull/732#issuecomment-1774565334

```
2023-10-22 21:15:40,673 1031 ERROR odoo odoo.addons.base_tier_validation_forward.tests.test_tier_validation: ERROR: TierTierValidation.test_01_forward_tier
Traceback (most recent call last):
  File "/__w/server-ux/server-ux/base_tier_validation_forward/tests/test_tier_validation.py", line 98, in test_01_forward_tier
    wizard = Form(
  File "/opt/odoo/odoo/tests/common.py", line 1957, in __init__
    self._init_from_defaults(self._model)
  File "/opt/odoo/odoo/tests/common.py", line 2039, in _init_from_defaults
    self._perform_onchange([])
  File "/opt/odoo/odoo/tests/common.py", line 2325, in _perform_onchange
    result = record.onchange(self._onchange_values(), fields, spec)
  File "/opt/odoo/odoo/models.py", line 6255, in onchange
    self.flush()
  File "/opt/odoo/odoo/models.py", line 5672, in flush
    self.recompute()
  File "/opt/odoo/odoo/models.py", line 6145, in recompute
    process(field)
  File "/opt/odoo/odoo/models.py", line 6129, in process
    field.recompute(recs)
  File "/opt/odoo/odoo/fields.py", line 1268, in recompute
    self.compute_value(recs)
  File "/opt/odoo/odoo/fields.py", line 1290, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/odoo/models.py", line 4269, in _compute_field_value
    fields.determine(field.compute, self)
  File "/opt/odoo/odoo/fields.py", line 87, in determine
    return needle(*args)
  File "/__w/server-ux/server-ux/base_tier_validation_report/models/tier_review.py", line 38, in _compute_resource_ref
    rec.resource_ref = (
  File "/opt/odoo/odoo/fields.py", line 1222, in __set__
    self.write(protected_records, value)
  File "/opt/odoo/odoo/fields.py", line 1040, in write
    cache_value = self.convert_to_cache(value, records)
  File "/opt/odoo/odoo/fields.py", line 2587, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for tier.review.resource_ref: 'tier.validation.tester,2'
 

```

The same test was passing before. Something has probably changed somewhere else.

## Module
base_tier_validation_report

attempted to fix it in: #733
But it is a hard one, as I cannot reproduce it locally.

Somebody here to the rescue?? :pray:

**Comment by LoisRForgeFlow** [comment]
Branch 15.0 CI has been fixed in https://github.com/OCA/server-ux/pull/737. You can rebase your open PRs to fix issues.
