### ISSUE TITLE
[12.0][Mass_Editing] Cannot Group-by -> Type, when adding fields

### ISSUE THREAD

**Issue by phatminh** [OCA/server-ux#91]
Hi, I think something wrong with `mass_editing_domain` when we use it.
When I adding fields for other models and filter **Group-by -> Type**.
I getting the following:

```python
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/code/projects/kodoo-12/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/code/projects/kodoo-12/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/code/projects/kodoo-12/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/code/projects/kodoo-12/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/code/projects/kodoo-12/odoo/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/code/projects/kodoo-12/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/code/projects/kodoo-12/odoo/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/code/projects/kodoo-12/odoo/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/code/projects/kodoo-12/odoo/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/code/projects/kodoo-12/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/code/projects/kodoo-12/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/code/projects/kodoo-12/odoo/odoo/api.py", line 745, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/code/projects/kodoo-12/odoo/odoo/api.py", line 718, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/code/projects/kodoo-12/odoo/odoo/models.py", line 2070, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/opt/odoo/code/projects/kodoo-12/odoo/odoo/models.py", line 2093, in _read_group_raw
    query = self._where_calc(domain)
  File "/opt/odoo/code/projects/kodoo-12/odoo/odoo/models.py", line 3896, in _where_calc
    e = expression.expression(domain, self)
  File "/opt/odoo/code/projects/kodoo-12/odoo/odoo/osv/expression.py", line 672, in __init__
    self.parse()
  File "/opt/odoo/code/projects/kodoo-12/odoo/odoo/osv/expression.py", line 853, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'mass_editing_domain' in leaf "<osv.ExtendedLeaf: ('mass_editing_domain', 'in', '[148]') on ir_model_fields (ctx: )>"
```

**Comment by JayVora-SerpentCS** [comment]
@Trivedi-Vacha-SerpentCS
